/* tslint:disable */
import './checkmark'
import './cross'
import './github'
import './heart'
import './instagram'
import './lamp'
import './linkedin'
import './menu'
import './shield'
import './twitter'
